bdr_management/urls.py
from django.urls import path
from django.views.generic import RedirectView

from bdr_management import views


urlpatterns = [
    path("", RedirectView.as_view(url="companies")),
    path("companies/", views.Companies.as_view(), name="companies"),
    path("companies/filter/", views.CompaniesFilter.as_view(), name="companies_filter"),
    path(
        "companies/delete/",
        views.CompanyDeleteMultiple.as_view(),
        name="companies_delete_multiple",
    ),
    path(
        "companies/export/excel/",
        views.CompaniesExcelExport.as_view(),
        name="companies_export",
    ),
    path(
        "companies/export/json/",
        views.CompaniesJsonExport.as_view(),
        name="companies_export_json",
    ),
    path(
        "companies/export/csv/",
        views.CompaniesCsvExport.as_view(),
        name="companies_export_csv",
    ),
    path(
        "companies/<int:pk>/",
        views.CompaniesManagementView.as_view(),
        name="companies_view",
    ),
    path(
        "companies/account/<str:account_uid>/<str:obligation_code>/",
        views.CompanyFilteredByAccountUID.as_view(),
        name="account_company",
    ),
    path(
        "username/companies/",
        views.CompaniesForUsernameView.as_view(),
        name="companies_for_username",
    ),
    path("companies/add/", views.CompanyAdd.as_view(), name="companies_add"),
    path(
        "companies/<int:pk>/edit/",
        views.CompaniesManagementEdit.as_view(),
        name="companies_edit",
    ),
    path(
        "companies/<int:pk>/delete/",
        views.CompanyDelete.as_view(),
        name="companies_delete",
    ),
    path(
        "companies/<int:pk>/persons/add/",
        views.PersonManagementCreate.as_view(),
        name="persons_add",
    ),
    path(
        "companies/<int:pk>/name-history/",
        views.CompanyNameHistory.as_view(),
        name="company_name_history",
    ),
    path(
        "companies/<int:pk>/comment/add/",
        views.CommentManagementCreate.as_view(),
        name="comment_add",
    ),
    path(
        "companies/<int:pk>/comment/<int:comment_pk>/delete/",
        views.CommentManagementDelete.as_view(),
        name="comment_delete",
    ),
    path(
        "companies/<int:pk>/reset/password/",
        views.ResetPassword.as_view(),
        name="reset_password",
    ),
    path(
        "companies/<int:pk>/reset_password_company_account/",
        views.ResetPasswordCompanyAccount.as_view(),
        name="reset_password_company_account",
    ),
    path(
        "companies/<int:pk>/set_company_account_owner/",
        views.SetCompanyAccountOwner.as_view(),
        name="set_company_account_owner",
    ),
    path(
        "companies/<int:pk>/create/account/",
        views.CreateAccount.as_view(),
        name="create_account",
    ),
    path(
        "companies/<int:pk>/create/reporting/folder/",
        views.CreateReportingFolder.as_view(),
        name="create_reporting_folder",
    ),
    path("persons/", views.Persons.as_view(), name="persons"),
    path("persons/filter/", views.PersonsFilter.as_view(), name="persons_filter"),
    path("persons/export/", views.PersonsExport.as_view(), name="persons_export"),
    path(
        "persons/export/json/",
        views.PersonsExportJson.as_view(),
        name="persons_export_json",
    ),
    path(
        "persons/<int:pk>/", views.PersonManagementView.as_view(), name="persons_view"
    ),
    path(
        "persons/<int:pk>/edit/",
        views.PersonManagementEdit.as_view(),
        name="persons_edit",
    ),
    path(
        "persons/<int:pk>/create/account/",
        views.CreateAccountPerson.as_view(),
        name="create_account_person",
    ),
    path(
        "persons/<int:pk>/disable/account/",
        views.DisableAccountPerson.as_view(),
        name="disable_account_person",
    ),
    path(
        "persons/<int:pk>/enable/account/",
        views.EnableAccountPerson.as_view(),
        name="enable_account_person",
    ),
    path(
        "persons/<int:pk>/delete/",
        views.PersonManagementDelete.as_view(),
        name="persons_delete",
    ),
    path(
        "companies/<int:cpk>/persons/<int:pk>/",
        views.PersonFromCompanyView.as_view(),
        name="person_from_company",
    ),
    path(
        "companies/<int:cpk>/persons/<int:pk>/edit/",
        views.PersonFromCompanyEdit.as_view(),
        name="person_from_company_edit",
    ),
    path(
        "companies/(<int:cpk>/persons/<int:pk>/delete/",
        views.PersonFromCompanyDelete.as_view(),
        name="person_from_company_delete",
    ),
    path("obligations/", views.Obligations.as_view(), name="obligations"),
    path("obligations/add/", views.ObligationCreate.as_view(), name="obligations_add"),
    path(
        "obligations/filter/",
        views.ObligationsFilter.as_view(),
        name="obligations_filter",
    ),
    path(
        "obligations/<int:pk>/", views.ObligationView.as_view(), name="obligation_view"
    ),
    path(
        "obligations/<int:pk>/edit/",
        views.ObligationEdit.as_view(),
        name="obligation_edit",
    ),
    path(
        "obligations/<int:pk>/delete/",
        views.ObligationDelete.as_view(),
        name="obligation_delete",
    ),
    path("templates/", views.EmailTemplates.as_view(), name="email_templates"),
    path(
        "templates/add/",
        views.EmailTemplateCreate.as_view(),
        name="email_templates_add",
    ),
    path(
        "templates/filter/",
        views.EmailTemplatesFilter.as_view(),
        name="email_templates_filter",
    ),
    path(
        "templates/<int:pk>/",
        views.EmailTemplateView.as_view(),
        name="email_template_view",
    ),
    path(
        "templates/<int:pk>/edit/",
        views.EmailTemplateEdit.as_view(),
        name="email_template_edit",
    ),
    path(
        "templates/<int:pk>/delete/",
        views.EmailTemplateDelete.as_view(),
        name="email_template_delete",
    ),
    path("settings/", views.Settings.as_view(), name="settings_view"),
    path("settings/edit/", views.SettingsEdit.as_view(), name="settings_edit"),
    path("actions/", views.Actions.as_view(), name="actions"),
    path(
        "actions/copy-report-status/",
        views.CopyReportingStatus.as_view(),
        name="copy_report_status",
    ),
]

bdr_registry/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

from bdr_management import views as management_views
from bdr_registry import views
from bdr_registry.views import api as api_views


admin.autodiscover()

company_patterns = [
    path("add/", views.CompanyCreate.as_view()),
    path("<int:pk>/", management_views.CompaniesUpdateView.as_view(), name="company"),
    path(
        "<int:pk>/update/",
        management_views.CompaniesUpdate.as_view(),
        name="company_update",
    ),
    path(
        "<int:pk>/persons/add/",
        management_views.PersonCreate.as_view(),
        name="person_add",
    ),
    path(
        "<int:pk>/comment/add/",
        management_views.CommentCreate.as_view(),
        name="comment_add",
    ),
    path(
        "<int:pk>/comment/<int:comment_pk>/delete/",
        management_views.CommentDelete.as_view(),
        name="comment_delete",
    ),
]

person_patterns = [
    path("<int:pk>/", management_views.PersonView.as_view(), name="person"),
    path(
        "<int:pk>/update/", management_views.PersonEdit.as_view(), name="person_update"
    ),
    path(
        "<int:pk>/delete/",
        management_views.PersonDelete.as_view(),
        name="person_delete",
    ),
]

password_set = [
    path(
        "request/",
        management_views.PasswordSetRequest.as_view(),
        name="person_set_request",
    ),
    path(
        "set_new_password/<str:token>/",
        management_views.PasswordSetNewPassword.as_view(),
        name="person_set_new_password",
    ),
]

urlpatterns = [
    path("", views.home.as_view(), name="home"),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="login.html"),
        name="login",
    ),
    path("accounts/logout/", views.logout_view, name="logout"),
    path("captcha/", include("captcha.urls")),
    path("self_register/", views.SelfRegister.as_view(), name="self_register"),
    path(
        "self_register_hdv/", views.SelfRegisterHDV.as_view(), name="self_register_hdv"
    ),
    path(
        "self_register/done/",
        TemplateView.as_view(template_name="self_register_done.html"),
        name="self_register_done",
    ),
    path(
        "self_register/done/hdv/",
        TemplateView.as_view(template_name="self_register_done_hdv.html"),
        name="self_register_done_hdv",
    ),
    path("crashme/", views.crashme),
    path("ping/", views.ping),
    path(
        "management/",
        include(("bdr_management.urls", "bdr_manangement"), namespace="management"),
    ),
    path("edit_company", views.edit_company),
    path("company/", include(company_patterns)),
    path("person/", include(person_patterns)),
    path("admin/", admin.site.urls),
    path("password_set/", include(password_set)),
    # Api views
    path(
        "api/company/obligation/<slug:obligation_slug>/",
        api_views.CompanyByObligationView.as_view(),
        name="api_company_by_obligation",
    ),
    path("organisation/all/", api_views.CompanyAllView.as_view()),
]
urlpatterns += staticfiles_urlpatterns()

management/urls.py
from django.conf.urls import patterns, url

from management.views import (Organisations, OrganisationsFilter,
                              OrganisationsView, OrganisationsEdit,
                              OrganisationDelete)

from management.views import (Persons, PersonsFilter, PersonsView,
                              PersonAdd, PersonEdit, PersonDelete)

from management.views.comments import CommentCreate, CommentDelete


urlpatterns = patterns(
    '',
    url(r'^organisations$', Organisations.as_view(), name='organisations'),
    url(r'^organisations/filter$', OrganisationsFilter.as_view(),
        name='organisations_filter'),
    url(r'^organisations/(?P<pk>\d+)$', OrganisationsView.as_view(),
        name='organisations_view'),
    url(r'^organisations/(?P<pk>\d+)/edit$', OrganisationsEdit.as_view(),
        name='organisations_edit'),
    url(r'^organisations/(?P<pk>\d+)/delete', OrganisationDelete.as_view(),
        name='organisations_delete'),
    url(r'^organisations/(?P<pk>\d+)/persons/add$', PersonAdd.as_view(),
        name='persons_add'),

    url(r'^organisations/(?P<pk>\d+)/comment/add', CommentCreate.as_view(),
        name='comment_add'),
    url(r'^organisations/(?P<organisation_id>\d+)/comment/(?P<pk>\d+)/delete$',
        CommentDelete.as_view(), name='comment_delete'),

    url(r'^persons$', Persons.as_view(), name='persons'),
    url(r'^persons/filter$', PersonsFilter.as_view(),
        name='persons_filter'),
    url(r'^persons/(?P<pk>\d+)$', PersonsView.as_view(),
        name='persons_view'),
    url(r'^persons/(?P<pk>\d+)/edit$', PersonEdit.as_view(),
        name='persons_edit'),
    url(r'^persons/(?P<pk>\d+)/delete', PersonDelete.as_view(),
        name='persons_delete'),

)

bdr_management/forms/comments.py
from django.forms import ModelForm
from bdr_registry.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

    def save(self, **kwargs):
        comment = super(CommentForm, self).save(commit=False)
        comment.company = self.initial["company"]
        comment.save()
        return comment

bdr_management/forms/email_template.py
from django.forms import ModelForm

from bdr_management.forms.utils import set_empty_label
from bdr_registry.models import EmailTemplate


class EmailTemplateForm(ModelForm):
    class Meta:
        model = EmailTemplate
        fields = ("name", "subject", "html_content")

    def __init__(self, *args, **kwargs):
        super(EmailTemplateForm, self).__init__(*args, **kwargs)
        set_empty_label(self.fields, "")

bdr_management/forms/utils.py
from django.forms import ModelChoiceField


def set_empty_label(fields, empty_label):
    for field_name in fields:
        field = fields[field_name]
        if isinstance(field, ModelChoiceField):
            field.empty_label = empty_label

bdr_management/views/comments.py
from braces.views import GroupRequiredMixin

from django.conf import settings
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext as _
from django.views import generic

from bdr_management import base, forms
from bdr_management.base import Breadcrumb

from bdr_registry.models import Company, Comment


class CommentCreateBase(SuccessMessageMixin, generic.CreateView):

    template_name = "bdr_management/comment_edit.html"
    form_class = forms.CommentForm
    model = Comment
    success_message = _("Comment added successfully")

    def dispatch(self, *args, **kwargs):
        self.company = get_object_or_404(Company, **self.kwargs)
        return super(CommentCreateBase, self).dispatch(*args, **kwargs)

    def get_form_kwargs(self, **kwargs):
        data = super(CommentCreateBase, self).get_form_kwargs(**kwargs)
        data["initial"]["company"] = self.company
        return data

    def get_context_data(self, **kwargs):
        context = super(CommentCreateBase, self).get_context_data(**kwargs)
        context["title"] = "Add a new comment"
        context["object"] = self.company
        return context


class CommentManagementCreate(GroupRequiredMixin, CommentCreateBase):

    group_required = settings.BDR_HELPDESK_GROUP
    raise_exception = True

    def get_context_data(self, **kwargs):
        back_url = self.get_success_url()
        breadcrumbs = [
            Breadcrumb(reverse("home"), title=_("Registry")),
            Breadcrumb(reverse("management:companies"), _("Companies")),
            Breadcrumb(back_url, self.company),
            Breadcrumb("", _("Add comment")),
        ]
        data = super(CommentManagementCreate, self).get_context_data(**kwargs)
        data["breadcrumbs"] = breadcrumbs
        data["cancel_url"] = back_url
        return data

    def get_success_url(self):
        return reverse("management:companies_view", kwargs=self.kwargs)


class CommentCreate(
    base.CompanyUserRequiredMixin, GroupRequiredMixin, CommentCreateBase
):

    group_required = settings.BDR_HELPDESK_GROUP
    raise_exception = True

    def get_context_data(self, **kwargs):
        back_url = self.get_success_url()
        breadcrumbs = [
            Breadcrumb(reverse("home"), title=_("Registry")),
            Breadcrumb(back_url, self.company),
            Breadcrumb("", _("Add comment")),
        ]
        data = super(CommentCreate, self).get_context_data(**kwargs)
        data["breadcrumbs"] = breadcrumbs
        data["cancel_url"] = back_url
        return data

    def get_success_url(self):
        return reverse("company", kwargs=self.kwargs)


class CommentDeleteBase(generic.DeleteView):

    pk_url_kwarg = "comment_pk"
    model = Comment

    def dispatch(self, request, *args, **kwargs):
        self.company = get_object_or_404(Company, pk=self.kwargs["pk"])
        return super(CommentDeleteBase, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        messages.success(request, _("Comment deleted"))
        return super(CommentDeleteBase, self).delete(request, *args, **kwargs)


class CommentManagementDelete(GroupRequiredMixin, CommentDeleteBase):

    group_required = settings.BDR_HELPDESK_GROUP
    raise_exception = True

    def get_success_url(self):
        return reverse("management:companies_view", kwargs={"pk": self.company.pk})


class CommentDelete(base.CompanyUserRequiredMixin, CommentDeleteBase):

    group_required = settings.BDR_HELPDESK_GROUP
    raise_exception = True

    def get_success_url(self):
        return reverse("company", kwargs={"pk": self.company.pk})

bdr_management/views/mixins.py
from django.core.exceptions import ObjectDoesNotExist

from bdr_registry.models import Account, Company, Obligation


class CompanyMixin(object):
    def get_obligations(self, default=True, no_user=False):
        if not no_user:
            obligations = self.request.user and self.request.user.obligations.values()
        else:
            obligations = False
            default = True
        if default and not obligations:
            obligations = Obligation.objects.values()
        return [o["id"] for o in obligations]

    def get_companies(self, default=True, no_user=False):
        o_ids = self.get_obligations(default=default, no_user=no_user)
        return Company.objects.filter(obligation__id__in=o_ids).all()

    def get_account(self, uid):
        try:
            return Account.objects.get(uid=uid)
        except ObjectDoesNotExist:
            return None

    def get_account_company(self, uid, obligation_code):
        account = self.get_account(uid)
        if account:
            try:
                return Company.objects.get(
                    account=account, obligation__code=obligation_code
                )
            except ObjectDoesNotExist:
                return None

    def dispatch(self, request, *args, **kwargs):
        # if request.user and not request.user.obligations.count():
        #     messages.warning(
        #         request, _('You have no obligations assigned to this user')
        #     )
        return super(CompanyMixin, self).dispatch(request, *args, **kwargs)

bdr_management/templates/_edit.html
{% load utils %}
{% load i18n %}
{% load widget_tweaks %}


{% include '_edit_header.html' %}

<form method="post">
  {% csrf_token %}

  <table>

    {% for field in form %}
      <tr>
        <td>
          <label for="id_{{ field.name }}"
            class="question {% if field.field.required %}required{% endif %}">{{ field.label }}</label>
        </td>
        <td>
          {{ field|add_error_class:"error" }}
          {% if field.name == 'eori' %}
            <div>
              <a href="http://ec.europa.eu/ecip/security_amendment/who_is_concerned/index_en.htm#eori">
                <small>{% trans "About EORI number" %}</small></a>
            </div>
          {% endif %}
        </td>
      </tr>
    {% endfor %}

    <tr>
      <td colspan="2">
        <button type="submit" class="primary_button">Save</button>
      </td>
    </tr>

  </table>

</form>

bdr_management/templates/comment_edit.html
{% extends '_management_base.html' %}
{% load widget_tweaks %}


{% block breadcrumbs %}

  <div class="breadcrumbitem">
    <a href="{% url 'home' %}">Registry</a>
  </div>

  <div class="breadcrumbitem">
    <a href="{% url 'management:organisations' %}">
      Organisations</a>
  </div>

  <div class="breadcrumbitem">
    <a href="{% url 'management:organisations_view' pk=object.pk %}">
      {{ object }}</a>
  </div>

  <div class="breadcrumbitemlast">
    Add comment
  </div>

{% endblock %}


{% block head %}

  <script src="{{ STATIC_URL }}ckeditor/ckeditor.js"></script>

  <style type="text/css">
    label {
      padding-bottom: 7px;
      display: block;
    }
  </style>

{% endblock %}


{% block content %}

  {% include '_edit_header.html' %}

  <form method="post">
    {% csrf_token %}
    <label for="{{ form.text.auto_id }}">
      <strong>{{ form.text.label }}</strong></label>
    {% render_field form.text %}<br><br>
    <button type="submit" class="primary_button">Save</button>

  <script>CKEDITOR.replace('id_text')</script>

  </form>

{% endblock %}

bdr_management/templates/organisation_edit.html
{% extends '_management_base.html' %}
{% load utils %}


{% block breadcrumbs %}

  <div class="breadcrumbitem">
    <a href="{% url 'home' %}">Registry</a>
  </div>

  <div class="breadcrumbitem">
    <a href="{% url 'management:organisations' %}">
      Organisations</a>
  </div>

  <div class="breadcrumbitem">
    <a href="{% url 'management:organisations_view' pk=object.pk %}">
      {{ object }}</a>
  </div>

  <div class="breadcrumbitemlast">
    Edit {{ object }}
  </div>

{% endblock %}


{% block content %}

  {% include '_edit.html' %}

{% endblock %}

bdr_management/templates/organisation_view.html
{% extends '_management_base.html' %}
{% load utils %}


{% block breadcrumbs %}

  <div class="breadcrumbitem">
    <a href="{% url 'home' %}">Registry</a>
  </div>

  <div class="breadcrumbitem">
    <a href="{% url 'management:organisations' %}">
      Organisations</a>
  </div>

  <div class="breadcrumbitemlast">
    {{ object }}
  </div>

{% endblock %}


{% block content %}

  {% include '_view.html' %}

  <h2>Comments</h2>
  <div class="sub-actions">
    <a href="{% url 'management:comment_add' object.pk %}" class="button">
      Add comment</a>
  </div>

  <table class="comment no-border">
    <tbody>

    {% for comment in object.comments.all %}
      <tr>
        <td class="content">
          <p>{{ comment.text|safe }}</p>
          <p class="documentByLine">{{ comment.created|date:"d b Y" }}</p>
        </td>
        <td class="action">
          <a class='delete-link' href="{% url 'management:comment_delete' organisation_id=object.pk pk=comment.pk %}">
            <small>Delete comment</small>
          </a>
        </td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="2">
          <p>There are no comments for this organisation.</p>
        </td>
      </tr>
    {% endfor %}

    </tbody>
  </table>

  <h2>Persons</h2>
  <div class="sub-actions">
    <a href="{% url 'management:persons_add' pk=object.pk %}"
       class="button">
      Add a new person</a>
  </div>

  <ul>

    {% for person in object.people.all %}
      <li>
        <a href="{% url 'management:persons_view' pk=person.pk %}">
          {{ person.formal_name }}</a>
      </li>
    {% endfor %}

  </ul>

{% endblock %}

bdr_management/templates/organisations.html
{% extends '_management_base.html' %}
{% load utils %}


{% block breadcrumbs %}

  <div class="breadcrumbitem">
    <a href="{% url 'home' %}">Registry</a>
  </div>

  <div class="breadcrumbitemlast">
    Organisations
  </div>

{% endblock %}


{% block content %}

  {% url 'management:organisations_filter' as url %}

  {% assign '["id", "name", "obligation", "account", "country", "vat_number", "date_registered"]' as columns %}
  {% assign '' as column_defs %}
  {% assign '[[7, "desc"]]' as column_sorting %}

  <h1>Organisations</h1>

  <div class="filters">
    {% include '_organisation_filters.html' %}
  </div>

  <table data-toggle='datatable' data-source='{{ url }}'
         data-columns='{{ columns }}'
         data-column-defs='{{ column_defs }}'
         data-column-sorting='{{ column_sorting }}'>

    <thead>
      <tr>
        <th>ID</th>
        <th>Company name</th>
        <th>Obligation</th>
        <th>Account</th>
        <th>Country</th>
        <th>VAT number</th>
        <th>Date registered</th>
      </tr>
    </thead>

  </table>

{% endblock %}

bdr_management/templates/person_add.html
{% extends '_management_base.html' %}
{% load widget_tweaks %}


{% block breadcrumbs %}

  <div class="breadcrumbitem">
    <a href="{% url 'home' %}">Registry</a>
  </div>

  <div class="breadcrumbitem">
    <a href="{% url 'management:organisations' %}">
      Organisations</a>
  </div>

  <div class="breadcrumbitem">
    <a href="{% url 'management:organisations_view' pk=object.pk %}">
      {{ object }}</a>
  </div>

  <div class="breadcrumbitemlast">
    Add person
  </div>

{% endblock %}



{% block content %}

  {% include '_edit.html' %}

{% endblock %}

bdr_management/templates/person_edit.html
{% extends '_management_base.html' %}
{% load widget_tweaks %}


{% block breadcrumbs %}

  <div class="breadcrumbitem">
    <a href="{% url 'home' %}">Registry</a>
  </div>

  <div class="breadcrumbitem">
    <a href="{% url 'management:organisations' %}">
      Persons</a>
  </div>

  <div class="breadcrumbitem">
    <a href="{% url 'management:persons_view' pk=object.pk %}">
      {{ object }}</a>
  </div>

  <div class="breadcrumbitemlast">
    Edit person
  </div>

{% endblock %}



{% block content %}

  {% include '_edit.html' %}

{% endblock %}

bdr_management/templates/person_view.html
{% extends '_management_base.html' %}
{% load utils %}


{% block breadcrumbs %}

  <div class="breadcrumbitem">
    <a href="{% url 'home' %}">Registry</a>
  </div>

  <div class="breadcrumbitem">
    <a href="{% url 'management:persons' %}">
      Persons</a>
  </div>

  <div class="breadcrumbitemlast">
    {{ object }}
  </div>

{% endblock %}


{% block content %}

  {% include '_view.html' %}

{% endblock %}

bdr_management/templates/persons.html
{% extends '_management_base.html' %}
{% load utils %}


{% block content %}

  {% url 'management:persons_filter' as url %}

  {% assign '["name", "email"]' as columns %}
  {% assign '' as column_defs %}

  <h1>Persons</h1>

  <table data-toggle='datatable' data-source='{{ url }}'
         data-columns='{{ columns }}'
         data-column-defs='{{ column_defs }}'>

    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>

  </table>

{% endblock %}