bdr_registry/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

from bdr_management import views as management_views
from bdr_registry import views
from bdr_registry.views import api as api_views


admin.autodiscover()

company_patterns = [
    path("add/", views.CompanyCreate.as_view()),
    path("<int:pk>/", management_views.CompaniesUpdateView.as_view(), name="company"),
    path(
        "<int:pk>/update/",
        management_views.CompaniesUpdate.as_view(),
        name="company_update",
    ),
    path(
        "<int:pk>/persons/add/",
        management_views.PersonCreate.as_view(),
        name="person_add",
    ),
    path(
        "<int:pk>/comment/add/",
        management_views.CommentCreate.as_view(),
        name="comment_add",
    ),
    path(
        "<int:pk>/comment/<int:comment_pk>/delete/",
        management_views.CommentDelete.as_view(),
        name="comment_delete",
    ),
]

person_patterns = [
    path("<int:pk>/", management_views.PersonView.as_view(), name="person"),
    path(
        "<int:pk>/update/", management_views.PersonEdit.as_view(), name="person_update"
    ),
    path(
        "<int:pk>/delete/",
        management_views.PersonDelete.as_view(),
        name="person_delete",
    ),
]

password_set = [
    path(
        "request/",
        management_views.PasswordSetRequest.as_view(),
        name="person_set_request",
    ),
    path(
        "set_new_password/<str:token>/",
        management_views.PasswordSetNewPassword.as_view(),
        name="person_set_new_password",
    ),
]

urlpatterns = [
    path("", views.home.as_view(), name="home"),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="login.html"),
        name="login",
    ),
    path("accounts/logout/", views.logout_view, name="logout"),
    path("captcha/", include("captcha.urls")),
    path("self_register/", views.SelfRegister.as_view(), name="self_register"),
    path(
        "self_register_hdv/", views.SelfRegisterHDV.as_view(), name="self_register_hdv"
    ),
    path(
        "self_register/done/",
        TemplateView.as_view(template_name="self_register_done.html"),
        name="self_register_done",
    ),
    path(
        "self_register/done/hdv/",
        TemplateView.as_view(template_name="self_register_done_hdv.html"),
        name="self_register_done_hdv",
    ),
    path("crashme/", views.crashme),
    path("ping/", views.ping),
    path(
        "management/",
        include(("bdr_management.urls", "bdr_manangement"), namespace="management"),
    ),
    path("edit_company", views.edit_company),
    path("company/", include(company_patterns)),
    path("person/", include(person_patterns)),
    path("admin/", admin.site.urls),
    path("password_set/", include(password_set)),
    # Api views
    path(
        "api/company/obligation/<slug:obligation_slug>/",
        api_views.CompanyByObligationView.as_view(),
        name="api_company_by_obligation",
    ),
    path("organisation/all/", api_views.CompanyAllView.as_view()),
]
urlpatterns += staticfiles_urlpatterns()

management/urls.py
from django.conf.urls import patterns, url

from management.views import (Organisations, OrganisationsFilter,
                              OrganisationsView, OrganisationsEdit,
                              OrganisationDelete)

from management.views import (Persons, PersonsFilter, PersonsView,
                              PersonAdd, PersonEdit, PersonDelete)

from management.views.comments import CommentCreate, CommentDelete


urlpatterns = patterns(
    '',
    url(r'^organisations$', Organisations.as_view(), name='organisations'),
    url(r'^organisations/filter$', OrganisationsFilter.as_view(),
        name='organisations_filter'),
    url(r'^organisations/(?P<pk>\d+)$', OrganisationsView.as_view(),
        name='organisations_view'),
    url(r'^organisations/(?P<pk>\d+)/edit$', OrganisationsEdit.as_view(),
        name='organisations_edit'),
    url(r'^organisations/(?P<pk>\d+)/delete', OrganisationDelete.as_view(),
        name='organisations_delete'),
    url(r'^organisations/(?P<pk>\d+)/persons/add$', PersonAdd.as_view(),
        name='persons_add'),

    url(r'^organisations/(?P<pk>\d+)/comment/add', CommentCreate.as_view(),
        name='comment_add'),
    url(r'^organisations/(?P<organisation_id>\d+)/comment/(?P<pk>\d+)/delete$',
        CommentDelete.as_view(), name='comment_delete'),

    url(r'^persons$', Persons.as_view(), name='persons'),
    url(r'^persons/filter$', PersonsFilter.as_view(),
        name='persons_filter'),
    url(r'^persons/(?P<pk>\d+)$', PersonsView.as_view(),
        name='persons_view'),
    url(r'^persons/(?P<pk>\d+)/edit$', PersonEdit.as_view(),
        name='persons_edit'),
    url(r'^persons/(?P<pk>\d+)/delete', PersonDelete.as_view(),
        name='persons_delete'),

)

bdr_registry/models.py
import requests
import random
import string
from unidecode import unidecode

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.urls import reverse
from django.db import models, transaction, IntegrityError
from django.utils.encoding import force_str
from django.utils.translation import gettext_lazy as _

from solo.models import SingletonModel
from bdr_registry.ldap_editor import create_ldap_editor
from .local import *
from post_office.models import EmailTemplate


def generate_key(size=20):
    crypto_random = random.SystemRandom()
    vocabulary = string.ascii_lowercase + string.digits
    return "".join(crypto_random.choice(vocabulary) for c in range(size))


class ApiKey(models.Model):

    key = models.CharField(max_length=255, default=generate_key)
    comment = models.CharField(max_length=255)

    def __str__(self):
        return self.comment


class Country(models.Model):

    name = models.CharField(max_length=255, unique=True)
    code = models.CharField(max_length=255, unique=True)

    class Meta(object):
        verbose_name_plural = "Countries"

    def __str__(self):
        return self.name


def validate_comma_separated_email_list(value):
    """
    Validate every email address in a comma separated list of emails.
    """
    value = force_str(value)

    emails = [email.strip() for email in value.split(",")]

    for email in emails:
        try:
            validate_email(email)
        except ValidationError:
            raise ValidationError("Invalid email: %s" % email, code="invalid")


class Obligation(models.Model):

    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255)
    reportek_slug = models.CharField(max_length=255)
    email_template = models.ForeignKey(EmailTemplate, on_delete=models.PROTECT)
    bcc = models.TextField(blank=True, validators=[validate_comma_separated_email_list])
    admins = models.ManyToManyField(User, related_name="obligations", blank=True)

    def __str__(self):
        return self.name

    @transaction.atomic
    def generate_account_id(self):
        query = NextAccountId.objects.select_for_update().filter(obligation=self)
        try:
            next_row = query[0]
        except IndexError:
            next_row = NextAccountId(obligation=self, next_id=1)
            next_row.save()
        value = next_row.next_id
        next_row.next_id += 1
        next_row.save()
        return value


class AccountManager(models.Manager):
    def create_for_obligation(self, obligation):
        next_id = obligation.generate_account_id()
        if hasattr(settings, "ACCOUNTS_PREFIX"):
            prefix = settings.ACCOUNTS_PREFIX
        else:
            prefix = ""
        uid = "{prefix}{o.code}{next_id}".format(
            prefix=prefix, o=obligation, next_id=next_id
        )
        return self.create(uid=uid)

    def create_for_person(self, company, person):
        uid = "{company}_{first_name}.{family_name}".format(
            company=company.account.uid,
            first_name=person.first_name.lower()[:3],
            family_name=person.family_name.lower()[:3],
        )
        uid = unidecode(uid)
        try:
            return self.create(uid=uid)
        except IntegrityError:
            uid = "{company}_{first_name}.{family_name}".format(
                company=company.account.uid,
                first_name=person.first_name.lower()[:4],
                family_name=person.family_name.lower()[:4],
            )
            uid = unidecode(uid)
            return self.create(uid=uid)


class Account(models.Model):

    uid = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.uid

    def set_random_password(self):
        self.password = generate_key(size=8)
        self.save()

    @property
    def exists_in_ldap(self):
        try:
            ldap_editor = create_ldap_editor()
            result = ldap_editor.search_account(self.uid)
            if result:
                return True
        except Exception as e:
            return False

    objects = AccountManager()

    @property
    def related_user(self):
        user = User.objects.filter(username=self.uid)
        if user:
            return user.first()

    class Meta:
        ordering = ["uid"]


class AccountUniqueToken(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    token = models.CharField(max_length=100)
    datetime = models.DateTimeField(auto_now_add=True)


class NextAccountId(models.Model):

    next_id = models.IntegerField()
    obligation = models.OneToOneField(
        Obligation, null=True, blank=True, on_delete=models.DO_NOTHING
    )

    def __str__(self):
        return "next_id={p.next_id} ({p.obligation.name})".format(p=self)


class Company(models.Model):
    class Meta:

        verbose_name_plural = "Companies"

    EORI_LABEL = _("Economic Operators Registration and Identification number (EORI)")

    name = models.CharField(_("Company name"), max_length=255)
    date_registered = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    outdated = models.BooleanField(default=False)
    addr_street = models.CharField(_("Street and number"), max_length=255, blank=True)
    addr_place1 = models.CharField(_("Municipality"), max_length=255, blank=True)
    addr_postalcode = models.CharField(_("Postal code"), max_length=255, blank=True)
    addr_place2 = models.CharField(_("Region"), max_length=255, null=True, blank=True)
    eori = models.CharField(
        _("EORI number"), help_text=EORI_LABEL, max_length=17, null=True, blank=True
    )
    vat_number = models.CharField(_("VAT number"), max_length=17, blank=True)
    world_manufacturer_identifier = models.CharField(
        _("World Manufacturer Identifier (WMI)"), max_length=20, blank=True
    )
    linked_hdv_company = models.OneToOneField(
        "Company",
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name="hdv_resim_company",
    )
    country = models.ForeignKey(
        Country, null=True, blank=True, on_delete=models.PROTECT
    )
    obligation = models.ForeignKey(
        Obligation, related_name="companies", on_delete=models.PROTECT
    )
    account = models.ForeignKey(
        Account,
        null=True,
        blank=True,
        on_delete=models.DO_NOTHING,
        related_name="companies",
    )
    website = models.URLField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse("company", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    def build_reporting_folder_path(self):
        if self.account:
            folder_path = "/{0}/{1}/{2}".format(
                self.obligation.reportek_slug, self.country.code, self.account.uid
            )
            return folder_path
        return ""

    def has_reporting_folder(self, folder_path=None):
        if hasattr(settings, "DISABLE_ZOPE_CONNECTION"):
            return False
        if folder_path is None:
            folder_path = self.build_reporting_folder_path()
        url = settings.BDR_API_URL + folder_path
        resp = requests.get(url)
        if resp.status_code == 200:
            return True
        else:
            return False

    @property
    def main_reporter(self):
        person = self.people.filter(is_main_user=True)
        if person:
            return person.first()

    @property
    def has_main_reporter(self):
        main_user = self.people.filter(is_main_user=True)
        if main_user:
            return True

    @property
    def can_edit(self):
        if self.obligation.code == "hdv":
            return settings.ENABLE_HDV_EDITING
        elif self.obligation.code == "hdv_resim":
            return settings.ENABLE_HDV_RESIM_EDITING
        else:
            return True


def organisation_loaded(instance, **extra):
    instance._initial_name = "" if instance.pk is None else instance.name


def organisation_saved(instance, **extra):
    if instance._initial_name != instance.name:
        try:
            user = local.get_request().user
        except AttributeError:
            user = None
        if user is not None and user.is_authenticated():
            user_id = user.id
        else:
            user_id = None
        instance.namehistory.create(name=instance.name, user_id=user_id)


models.signals.post_init.connect(organisation_loaded, sender=Company)
models.signals.post_save.connect(organisation_saved, sender=Company)


class CompanyNameHistory(models.Model):

    name = models.CharField(max_length=255)
    company = models.ForeignKey(
        Company, related_name="namehistory", on_delete=models.CASCADE
    )
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.DO_NOTHING)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{h.name} {h.time} {h.user}".format(h=self)


class Person(models.Model):

    title = models.CharField(_("Title"), max_length=255, null=True, blank=True)
    family_name = models.CharField(_("Family name"), max_length=255)
    first_name = models.CharField(_("First name"), max_length=255)

    email = models.EmailField(_("Email address"))

    phone = models.CharField(_("Telephone"), max_length=255, blank=True)
    phone2 = models.CharField(_("Telephone 2"), max_length=255, null=True, blank=True)
    phone3 = models.CharField(_("Telephone 3"), max_length=255, null=True, blank=True)
    fax = models.CharField(_("Fax"), max_length=255, null=True, blank=True)
    account = models.ForeignKey(
        Account,
        null=True,
        blank=True,
        on_delete=models.DO_NOTHING,
        related_name="persons",
    )
    is_main_user = models.BooleanField(default=False)

bdr_management/forms/organisations.py
from django.forms import BooleanField, Form, ModelForm, ModelChoiceField
from bdr_registry.models import Company


class OrganisationForm(ModelForm):

    class Meta():
        model = Company
        exclude = ('id',)
        empty_label = ""

    def __init__(self, *args, **kwargs):
        super(OrganisationForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields[field_name]
            if isinstance(field, ModelChoiceField):
                field.empty_label = ''


class OrganisationDeleteForm(Form):

    delete_reporting_folder = BooleanField()
    delete_account = BooleanField()

bdr_registry/forms.py
from captcha.fields import CaptchaField

from django.forms.models import ModelForm

from bdr_registry import models
from bdr_management.forms.utils import set_empty_label

ORG_CREATE_EXCLUDE = ("account", "active", "comments")


class CompanyHDVForm(ModelForm):

    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super(CompanyHDVForm, self).__init__(*args, **kwargs)
        set_empty_label(self.fields, "")
        self.fields["world_manufacturer_identifier"].required = True

    class Meta:
        model = models.Company
        fields = [
            "name",
            "addr_street",
            "addr_place1",
            "addr_postalcode",
            "country",
            "world_manufacturer_identifier",
        ]


class PersonHDVForm(ModelForm):
    class Meta:
        model = models.Person
        fields = ["title", "family_name", "first_name", "email", "phone"]

bdr_registry/templates/comment_confirm_delete.html
{% extends "bdr_layout.html" %}


{% block content %}

<h1>Delete comment</h1>

<form method="post">
  {% csrf_token %}
  <p>
    About to delete the following comment
    created on {{ object.created|date:"d F Y" }}:
    <blockquote>
      {{ object.text|safe }}
    </blockquote>
    <button type="submit">Delete</button>
  </p>
</form>

{% endblock %}

bdr_registry/templates/comment_update.html
{% extends "bdr_layout.html" %}
{% load i18n %}

{% block content %}

<h1>{% trans "Update comment" %}</h1>

<form method="post">
  {% csrf_token %}
  {{ form.media }}
  <p>
    {% for field in form %}
      <label for="id_{{ field.name }}" class="question
          {% if field.field.required %}required{% endif %}">
        {{ field.label }}
      </label>
      {% for err in field.errors %}
        <div class="bdr-error">{{ err }}</div>
      {% endfor %}
      {{ field }}
    {% endfor %}
  </p>
  <button type="submit">{% trans "Save" %}</button>

  <a href="{% url 'company_update' comment.company.pk %}">{% trans "Back" %}</a>


</form>

{% endblock %}

bdr_registry/templates/company.html
{{ object }}

bdr_registry/templates/company_add_person.html
{% extends "bdr_layout.html" %}
{% load i18n %}

{% block content %}

<h1>{% trans "Add person" %}</h1>

<form method="post">
  {% csrf_token %}

  <table class="formtable">
  <col style="width:10em"/>
  {% for field in form %}
    <tr>
      <td>
        <label for="id_{{ field.name }}" class="question
            {% if field.field.required %}required{% endif %}">
          {{ field.label }}
        </label>
      </td>
      <td>
        {% for err in field.errors %}
          <div class="bdr-error">{{ err }}</div>
        {% endfor %}
        {{ field }}
      </td>
    </tr>
  {% endfor %}
  </table>

  <button type="submit">{% trans "Save" %}</button>

  <a href="{% url 'company_update' organisation_pk %}">{% trans "Back" %}</a>

</form>

{% endblock %}

bdr_registry/templates/company_name_history.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_modify %}
{% load admin_urls %}


{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_label|capfirst|escape }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}{{ company.pk }}">{{ company|truncatewords:"18" }}</a>
&rsaquo; name history
</div>
{% endblock %}


{% block content %}
<h1>History of name updates for <em>{{ company.name }}</em></h1>

<table>

  <thead>
    <tr>
      <th>Time</th>
      <th>User</th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    {% for item in company.namehistory.all %}
      <tr>
        <td>{{ item.time }}</td>
        <td>{% firstof item.user '(automated script)' %}</td>
        <td>{{ item.name }}</td>
      </tr>
    {% endfor %}
  </tbody>

</table>

{% endblock %}

bdr_registry/templates/company_update.html
{% extends "bdr_layout.html" %}
{% load static from staticfiles %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}


<div id="operations">
  <ul>
    {% if reporting_url %}
    <li><a href="{{ reporting_url }}"
           title="Go back to the collection for this company"
           >{% trans "Back to reporting" %}</a></li>
    {% endif %}
  </ul>
</div>


<h1>{% trans "Update company" %} <em>{{ object.name }}</em></h1>


<h2>{% trans "Company details" %}</h2>

<form method="post">
  {% csrf_token %}

  <table class="formtable">
  <col style="width:10em"/>

  {% if not form.fields.name %}
    <tr>
      <td>
        <label for="id_name" class="question">{% trans "Company name" %}</label>
      </td>
      <td>
        <input id="id_name" value="{{ object.name }}" disabled>
        <br>
        <span class="input-hint">
          {% trans "To modify company name, please contact" %}
          <a href="mailto:{{ helpdesk_email }}">{% trans "helpdesk" %}</a>.
        </span>
      </td>
    </tr>
  {% endif %}

  {% for field in form %}

    <tr>
      <td>
        <label for="id_{{ field.name }}" class="question
            {% if field.field.required %}required{% endif %}">
          {{ field.label }}
        </label>
      </td>
      <td>
        {% for err in field.errors %}
          <div class="bdr-error">{{ err }}</div>
        {% endfor %}
        {% if field.help_text %}
          {% render_field field title=field.help_text %}
        {% else %}
          {{ field }}
        {% endif %}
        {% if field.name == 'eori' %}
          <div>
            <a href="http://ec.europa.eu/ecip/security_amendment/who_is_concerned/index_en.htm#eori">
              <small>{% trans "About EORI number" %}</small></a>
          </div>
        {% endif %}
      </td>
    </tr>

  {% endfor %}

  <tr>
      <td>
        <label for="id_country" class="question">{% trans "Country" %}</label>
      </td>
      <td>
        <input id="id_country" value="{{ object.country.name }}" disabled>
      </td>
    </tr>
  </tr>

  <tr>
      <td>
        <label for="id_account" class="question">{% trans "Account name" %}</label>
      </td>
      <td>
        <input id="id_account" value="{{ object.account.uid }}" disabled>
      </td>
    </tr>
  </tr>

  <tr>
      <td>
        <label for="id_obligation" class="question">{% trans "Obligation" %}</label>
      </td>
      <td>
        <input id="id_obligation" value="{{ object.obligation.name }}" disabled>
      </td>
    </tr>
  </tr>

  </table>

  <button type="submit">{% trans "Save" %}</button>

</form>


<h2>{% trans "Comments" %}</h2>

<ul>
{% for comment in company.comments.all %}
  <li>
    <a href="{% url 'comment_update' comment.pk %}">
        {{ comment.created|date:"d F Y" }}
    </a>
    <a class="delete" href="{% url 'comment_delete' comment.pk %}">
      <img src="{% static "admin/img/icon_deletelink.gif" %}">
    </a>
    <p>
    {{ comment.text |linebreaksbr }}
    </p>
  </li>
{% endfor %}
</ul>

<form action="{% url 'organisation_add_comment' company.pk %}">
  <button type="submit">{% trans "New comment" %}</button>
</form>


<h2>{% trans "People" %}</h2>

<ul>
{% for person in company.people.all %}
  <li>
    <a href="{% url 'person_update' person.pk %}">{{ person }}</a>
    <a class="delete" href="{% url 'person_delete' person.pk %}">
      <img src="{% static "admin/img/icon_deletelink.gif" %}">
    </a>
  </li>
{% endfor %}
</ul>

<form action="{% url 'organisation_add_person' company.pk %}">
  <button type="submit">{% trans "New person" %}</button>
</form>

{% endblock %}

bdr_registry/templates/email_company_fgas.html
<html>
<head>
  <meta charset="utf-8">
</head>

<body>
  <p>Dear {{ person.formal_name }},</p>

  <p>
    This message is addressed to you as the contact person of an
    undertaking that needs to report data on fluorinated greenhouse
    gases (F-Gases) under Article 6 of Regulation (EC) No 842/2006.
  </p>

  <p>
    The report needs to be submitted to the European Environment Agency
    (EEA) using the online Business Data Repository (BDR) at <a
    href="https://bdr.eionet.europa.eu/">bdr.eionet.europa.eu</a>.
  </p>

  <p>
    In order to submit your report you will need to login using the
    username and password for your company. The company for which you
    have received reporting rights is <b>{{ company.name }}</b> in
    <b>{{ company.country.name }}</b>. The username for your
    company is: <b>{{ company.account.uid }}</b> and the password
    is <b>{{ company.account.password }}</b>.
  </p>

  <p>
    Please note that this password will be valid for reporting during the
    year {{ reporting_year }}.  To assure confidentiality we will reset the password at
    the beginning of {{ next_year }}.
  </p>

  <p><u>How to submit your report?</u></p>

  <p>
    Detailed information on how to upload your delivery to BDR is
    available at: <a
    href="https://bdr.eionet.europa.eu/help/upload.html"
    >bdr.eionet.europa.eu/help/upload.html</a>.
  </p>

  <p><u>Reporting requirements and forms</u></p>

  <p>
    From this year the EEA is using online webforms to collect the data
    you need to submit. This allows amongst others the data to be fed
    directly into a database without the need for manual processing. The
    webforms can perform certain checks immediately while you are
    completing the form or immediately after submission. This will
    increase the user friendliness and reduce the administrative burden
    for all stakeholders. It will also reduce the number of questions
    posed to you after submission. While the webforms by nature will
    look somewhat different from the Excel sheets used so far, no
    additional data will be requested compared to previous years. Due to
    the functionality of the online forms it was possible to eliminate
    certain tables and to avoid that data needs to be repeated in two
    different forms.
  </p>

  <p>
    Reporting is not required if you produce, import or export less than
    one tonne of fluorinated greenhouse gases.
  </p>

  <p><u>BDR Helpdesk</u></p>

  <p>
    Please feel free to contact the BDR Helpdesk (<a
    href="mailto:BDR.helpdesk@eea.europa.eu"
    >BDR.helpdesk@eea.europa.eu</a>):
  </p>

  <ul>
    <li>
      if you received this e-mail but you think that you are no longer
      subject to the reporting obligations, please be so kind to inform
      us accordingly.
    </li>

    <li>
      for technical assistance with access to BDR and the submission
      process.
    </li>
  </ul>

  <p>Thank you in advance for your co-operation.</p>

  <p>
    Yours faithfully<br />
    BDR Helpdesk
  </p>
</body>
</html>

bdr_registry/templates/email_organisation_cars.html
<html>
<head>
  <meta charset="utf-8">
</head>

<body>
  <p>Dear {{ person.formal_name }},</p>

  <p>
    This message is addressed to you as the contact person of a manufacturer
    reporting data concerning CO2 emissions from passenger cars in accordance with Article 8(5) of Regulation (EU) No 443/2009.
  </p>

  <p>
    The report shall be submitted to the European Environment Agency
    (EEA) using the online Business Data Repository (BDR) at <a
    href="https://bdr.eionet.europa.eu/">bdr.eionet.europa.eu</a>.
  </p>

  <p>
    In order to submit your report you will need to login using the
    username and password for your company.
    The company for which you have received reporting rights is
    <strong>{{ organisation.name }}</strong> in
    <strong>{{ organisation.country.name }}</strong>.

    The username for your company is:
    <strong>{{ organisation.account.uid }}</strong> and the password
    is <strong>{{ organisation.account.password }}</strong>.
  </p>

  <p>
    Please note that this password will be valid for reporting during
    the year {{ reporting_year }}.
    To assure confidentiality we will reset the password at the beginning
    of {{ next_year }}.
  </p>

  <p><u>How to submit your report?</u></p>

  <p>
    Detailed information on how to upload your delivery to BDR
    is available in the BDR User Manual at: <a
    href="https://circabc.europa.eu/w/browse/a41f7626-c660-4ee6-9b4b-8f198de8ab5c">https://circabc.europa.eu/w/browse/a41f7626-c660-4ee6-9b4b-8f198de8ab5c</a>.
  </p>

  <p><u>Reporting requirements and forms</u></p>

  <p>
    From this year the EEA is collecting the corrections from cars
    manufacturers using the BDR. When notifying corrections back to
    the Commission, the manufacturer must include all records and all entries
    that are relevant for it; i.e. both those that the manufacturer considers correct as well as those that have been corrected.

    For 2014, manufacturers can provide data in several formats: .xls, .csv,
    .xml, .mdb.
  </p>

  <p><u>BDR Helpdesk</u></p>

  <p>
    Please feel free to contact the BDR Helpdesk (<a
    href="mailto:BDR.helpdesk@eea.europa.eu"
    >BDR.helpdesk@eea.europa.eu</a>)
  </p>

  <p>
    If you received this e-mail but you think that you are no longer
    subject to the reporting obligations, please be so kind to inform
    us accordingly.
  </p>

  <p>Thank you in advance for your co-operation.</p>

  <p>
    Yours faithfully<br />
    BDR Helpdesk
  </p>
</body>
</html>

bdr_registry/templates/login.html
{% extends "bdr_layout.html" %}
{% load i18n %}


{% block content %}

{% if form.errors %}
  <p>{% trans "Your username and password didn't match. Please try again." %}</p>
{% endif %}

<h1>{% trans "Log in" %}</h1>

<form method="post" action="{% url 'login' %}">
  {% csrf_token %}
  <table>
    <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
    </tr>
    <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
    </tr>
  </table>

  <input type="hidden" name="next" value="{{ next }}" />
  <button type="submit">{% trans "login" %}</button>
</form>

{% endblock %}